# This is the CI matrix that runs per push event
# for tests not requiring big data.

trigger:
- master

jobs:
- job: 'EggInfo'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0

  # Make sure that egg_info works without dependencies
  - script: |
      python -m pip install --upgrade pip setuptools
      python setup.py egg_info
    displayName: 'egg_info'

- job: 'PEP8'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m pip install --upgrade pip setuptools
      pip install flake8
      flake8 acstools --count
    displayName: 'PEP 8 check'

- job: 'Doc'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: |
      python -m pip install --upgrade pip setuptools
      pip install numpydoc matplotlib sphinx-automodapi sphinx_rtd_theme
      python setup.py install
      cd doc
      make html
    displayName: 'Doc build'
