name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly Tuesday 6 AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 6 * * 2'

jobs:
  initial_checks:
    name: Mandatory checks before CI
    runs-on: ubuntu-latest
    steps:
    - name: Check base branch
      uses: actions/github-script@v3
      if: github.event_name == 'pull_request'
      with:
        script: |
          const allowed_basebranch = 'master';
          const pr = context.payload.pull_request;
          if (pr.base.ref !== allowed_basebranch) {
            core.setFailed(`PR opened against ${pr.base.ref}, not ${allowed_basebranch}`);
          } else {
            core.info(`PR opened correctly against ${allowed_basebranch}`);
          }

  # The rest only run if above are done

  pep_and_audit:
    runs-on: ubuntu-latest
    needs: initial_checks
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip flake8
        flake8 acstools --count
    # Make sure that packaging will work
    - name: pep517 build
      run: |
        python -m pip install --upgrade setuptools build "twine>=3.3"
        python -m build --sdist .
        twine check --strict dist/*
    - name: Security audit
      run: |
        python -m pip install --upgrade bandit
        bandit -r . -c .bandit.yaml

  tests:
    runs-on: ubuntu-latest
    needs: initial_checks
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .[test,all]
    - name: Test
      run: pytest --remote-data -v

  dev_deps_tests:
    runs-on: ubuntu-latest
    needs: initial_check
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install git+https://github.com/astropy/astropy.git#egg=astropy --upgrade --no-deps
        python -m pip install -e .[test,all]
    - name: Test
      run: pytest --remote-data -v

  link_check:
    runs-on: ubuntu-latest
    needs: initial_checks
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .[docs]
    - name: Docs link check
      run: |
        cd doc
        make linkcheck
      shell: bash
